version: "3"

services:
  LineArrowAndCirco:
    container_name: LineArrowAndCirco
    build:
      context: ./
      dockerfile: ./Dockerfile
      labels:
        com.example.description: "LineArrowAndCirco"
        com.example.department: "HCD Lab"
        com.example.label-with-empty-value: ""
    image: wujiamin/landa:1.0
    volumes:
      - ./out:/srv/app/out
      - ./lib:/srv/app/lib
    storage_opt:
      size: "20G"
    restart: unless-stopped
    network_mode: bridge
    hostname: LineArrowAndCirco
